### ISSUE TITLE
Back End Issue

### ISSUE THREAD

**Issue by mazurooo** [jamespfennell/transiter#131]
Apologies on bugging you, your software is amazing.  Any ideas on why all lines show "backend error"?  Is this related to the MTA's url changing?

**Comment by jamespfennell** [comment]
Hey, you're not bugging at all, that's the point of the issue tracker :)

Could you post the full error you're seeing? How often are you seeing it? One of the MTA URLs did change recently. Updating the NYC subway transit system should fix it.

**Comment by da555nny** [comment]
`{
  "code": 13,
  "message": "internal error",
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.Status",
      "code": 2,
      "message": "failed to connect to `host=postgres user=transiter database=transiter`: hostname resolving error (lookup postgres: Temporary failure in name resolution)",
      "details": []
    }
  ]
}`

**Comment by kungpaogao** [comment]
+1 seeing the same error on realtimerail.nyc

**Comment by jamespfennell** [comment]
Oh sorry, I misunderstood the issue. I thought you were seeing these errors when running Transiter yourself. I wasn't aware realtimerail.nyc was down.

It's working again now. The problem was that the logs for the Caddy reverse proxy eventually grew to consume all of the hard disk on the machine it's deployed on, so everything stopped working. I've cleared the logs and it's working again. I'll configure and email or alert so that I see this happening in advance.

Thanks for the report!

**Comment by mazurooo** [comment]
Thank you sir!  The guys in the warehouse thank you...
